### ISSUE TITLE
The plugin interfers with gn/gN

### ISSUE THREAD

**Issue by KabbAmine** [Shougo/neco-vim#1]
I don't know why, but it looks like that neco-vim interferes with `gn`/`gN`.

Xubuntu 14.04
(G)Vim 7.4.52
## How to reproduce

With the following example and being on the first 'foo':

``` vim
let g:foo = 'foo'
let s:foo = 'foo'

function s:Bar(foo)
endfunction
```
1. Search for 'foo' using `*`
2. Using `gn`, replace the first occurrence with 'bar':  `cgnbar`
3. Repeat the command with `.`

The next 'foo' will be replaced by 'r' instead of 'bar'.

**With neco-vim**

![with-neco](https://cloud.githubusercontent.com/assets/5658084/13266396/f77c2e22-da88-11e5-8f5c-5bd2f3e151ec.gif)

**Without neco-vim**

![without-neco](https://cloud.githubusercontent.com/assets/5658084/13266400/fc7a1da8-da88-11e5-9ade-92814adc2b30.gif)
## What expected

Repeating the process with `.` should replace the next occurrence of 'foo' with 'bar' as showed in the 2nd gif.

**Comment by Shougo** [comment]
Your Vim version is too old.
This is fixed on latest Vim.

**Comment by KabbAmine** [comment]
Thanks, I've updated vim to 7.4.882 and everything works fine now :+1:
