### ISSUE TITLE
Deoplete completion

### ISSUE THREAD

**Issue by eugen0329** [Shougo/neco-vim#2]
Can't achieve step-by-step completion behaviour like on the screenshot. Seem, the problem is with candidates sorting.

https://camo.githubusercontent.com/4a4d1893ce150863dd815fa6967e5f526ac84727/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3231343438382f3632333439362f39346564313961322d636636382d313165322d386433332d3361616438613339643763312e676966

**Comment by Shougo** [comment]
It is deoplete feature.
The feature is not supported in deoplete.
