### ISSUE TITLE
load C header files when they are introduced in file

### ISSUE THREAD

**Issue by ghost** [Shougo/neco-vim#5]
I've tried to find a solution to this in closed issues and elsewhere online but could not get a solution.
I want neocomplete to target header contents for completion when I type even when the target has not been introduced before.
Scenario:
  Launch a fresh vim session and create and edit a new file.c and include <stdio.h> . I then create  the first function and the first statement is a call to printf. I want neocomplete to suggest print, printf etc when I type pr for this first time.

Below is the part of my vimrc regarding neocomplete.

    let g:neocomplete#enable_at_startup=1
   
    "enable smartcase
    let g:neocomplete#enable_smart_case=1
   
    "set minimum length of keyword to be target of completion
    let g:neocomplete#min_keyword_legth=3
   
    "insert delimiters automatically (/ for filenames # for vimscript)
    let g:neocomplete#enable_auto_delimiter=1
   
    let g:neocomplete#sources#dictionary#dictionaries = {
            \'default' : '',
            \'vimshell' : $HOME.'/.vimshell_hist',
            \'scheme' : $HOME.'/.gosh_completions'}
   
    " Define keyword.
    if !exists('g:neocomplete#keyword_patterns')
            let g:neocomplete#keyword_patterns = {}
    endif
   
    let g:neocomplete#keyword_patterns['default'] = '\h\w*'
   
    if !exists('g:neocomplete#sources#omni#input_patterns')
            let g:neocomplete#sources#omni#input_patterns = {}
    endif
   
    let g:neocomplete#sources#omni#input_patterns.c= '[^.[:digit:] *\t]\%(\.\|->\)'
   
    "press enter to close popup
    inoremap <expr><cr> pumvisible() ? "\<C-y>" : "\<cr>"
   
    "For smart TAB completion.
    inoremap <expr><TAB>  pumvisible() ? "\<C-n>" :<SID>check_back_space() ? "\<TAB>" :neocomplete#start_manual_complete()
   
    function! s:check_back_space() "{{{
            let col = col('.') - 1
            return !col || getline('.')[col - 1]  =~# '\s'
    endfunction"}}}
  
    let g:neoinclude#ctags_commands={'_':'/usr/bin/ctags'}

I have ctags and the neoinclude plugin installed

**Comment by Shougo** [comment]
It is neoinclude? issue.
It is not neco-vim issue.

**Comment by Shougo** [comment]
You should read neocomplete issue template.
The reproduce ways from Vim starting and the minimal vimrc are needed.

**Comment by Shougo** [comment]
neoinclude plugin and vimproc plugin installation is needed.
And it takes some time to make cache.

**Comment by ghost** [comment]
I do have both neoinclude and vimproc plugins installed. And it taking some time, I would have expected it to be some seconds as just like jeanbroid in this issue -> https://github.com/Shougo/neocomplete.vim/issues/118 raised, vim's C-p does have them loaded and targets them.

**Comment by ghost** [comment]
Oh, definitely in the wrong repo, but..

**Comment by Shougo** [comment]
> I do have both neoinclude and vimproc plugins installed. And it taking some time, I would have expected it to be some seconds as just like jeanbroid in this issue -> Shougo/neocomplete.vim#118 raised, vim's C-p does have them loaded and targets them.

Really?  I cannot reproduce it.
You should check `'path'` option is set correctly.

**Comment by Shougo** [comment]
neoinclude generates `neoinclude#include#get_tag_files()` tags files.
And the detected header files list is `neoinclude#include#get_include_files()`.

**Comment by ghost** [comment]
With my path as the default '.,/usr/include,,' , a buffer with only <stdio.h> included will have neoinclude#include#get_current_include_files() return a list of ['/usr/include/stdio.h', '/usr/include/features.h', '/usr/include/libio.h', '/usr/include/bits/types.h']  but neoinclude#include#get_tag_files() returning an empty list.

neoinclude#include#get_include_files returns a list containing the path to the file in the buffer

**Comment by Shougo** [comment]
The tags files are not generated.
The generate is asynchronous.

You should check include.vim implementation.

https://github.com/Shougo/neoinclude.vim/blob/master/autoload/neoinclude/include.vim#L118

The ctags is executable?
And you can check `s:initialize_include()`.
I cannot debug your environment.
But you can debug it.
It is open source.
